import iconCore from "../../assets/images/iconCore.svg";
import iconBoosted from "../../assets/images/iconBoosted.svg";
import iconGold from "../../assets/images/iconGold.png";
import iconx from "../../assets/images/iconx.png";
import iconPing from "../../assets/images/iconPing.png";
import iconLion from "../../assets/images/iconLion.png";
import iconAr from "../../assets/images/iconAr.png";
import iconFarm1 from "../../assets/images/iconFarm1.png";

export const farmValue = [
  {
    id: 0,

    img: iconFarm1,
    name: "CAKE-BNB",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "20.81%",

    upto: "upto",
    upPerc: "43%",
    liquidity: "liquidity",
    value: 1999999,
    multi: "multiplier",
    perc: "40x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },

  {
    id: 1,
  
    img: iconFarm1,
    name: "CAKE-BUSD",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "20,76%",

    upto: "upto",
    upPerc: "37,71%",
    liquidity: "liquidity",
    value: 15.256,
    multi: "multiplier",
    perc: "2.5x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },
  {
    id: 2,
    img: iconFarm1,
    name: "CAKE-USDT",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "22,76%",

    upto: "upto",
    upPerc: "41.09%",
    liquidity: "liquidity",
    value: 10.621,
    multi: "multiplier",
    perc: "2x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },
  {
    id: 3,
    img: iconGold,
    name: "BUSD-BNB",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "16.43%",

    upto: "upto",
    upPerc: "43%",
    liquidity: "liquidity",
    value: 174.568,
    multi: "multiplier",
    perc: "11x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },
  {
    id: 4,
    img: iconx,
    name: "XCAD-CAKE",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "47.55%",

    upto: "upto",
    upPerc: "43%",
    liquidity: "liquidity",
    value: 427.75,
    multi: "multiplier",
    perc: "0.2x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },
  {
    id: 5,
    img: iconLion,
    name: "WMX-BUSD",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "124.81%",

    upto: "upto",
    upPerc: "43%",
    liquidity: "liquidity",
    value: 615.268,
    multi: "multiplier",
    perc: "0.5x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },
  {
    id: 6,
    img: iconAr,
    name: "ARV-BNB",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "95.95%",

    upto: "upto",
    upPerc: "43%",
    liquidity: "liquidity",
    value: 146.786,
    multi: "multiplier",
    perc: "0.1x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },
  {
    id: 7,
    img: iconPing,
    name: "MGP-BUSD",
    imgCore: iconCore,
    Core: "Core",
    imgBoosted: iconBoosted,
    Boosted: "Booster",
    earned: "Earned",
    number: 0,
    APR: "APR",
    numberApr: "112.81%",

    upto: "upto",
    upPerc: "43%",
    liquidity: "liquidity",
    value: 469.362,
    multi: "multiplier",
    perc: "0.5x",
    ancorCake: "Get CAKE-BNB LP",
    ancorContract: "View Contract",
    ancorInfo: "See Pair Info",
    titleCake:"CAKE",
    titleEarned:"EARNED",
    numberEarned: 0.00000,
    btnHarvest: "Harvest",
    titleYield: "YIELD BOOSTER",
    uptoh2: "Up to x2",
    paraYield: "Connect wallet to activate yield booster",
    nameBtn: "START FARMING",
  },
];
