export const languageListObj = [
    {language: "বাংলা" },
    {language: "العربية" },
    {language: "English" },
    {language: "Deutsch" },
    {language: "Ελληνικά" },
    {language: "Español" },
    {language: "Suomalainen" },
    {language: "Filipino" },
    {language: "Français" },
    {language: "हिंदी" },
    {language: "Magyar" },
    {language: "Bahasa Indonesia" },
    {language: "Itliano" },
    {language: "日本語" },
    {language: "한국어" },
    {language: "Nederlands" },
    {language: "Polski" },
    {language: "Português (Brazil)" },
    {language: "Português" },
    {language: "Română" },
    {language: "Русский" },
    {language: "Svenska" },
    {language: "தமிழ்" },
    {language: "Türkçe" },
    {language: "Українська" },
    {language: "Tiếng Việt" },
    {language: "简体中文" },
    {language: "繁體中文" }
]

