import iconFarm1 from "../../assets/images/iconFarm1.png";


import xIcon from "../../assets/images/xIcon.png";
import iconpi from "../../assets/images/iconpi.png"
import iconLeon from "../../assets/images/iconLeon.png"
import iconsr from "../../assets/images/iconsr.png"

export const poolsValue = [{
        eventkey: "0",
        id: 0,
        class: "btn-cake-acc",
        imgFarm: iconFarm1,
        title: "Stake-CAKE",
        paraPool: "Stake, Earn – And more!",
        poolstaked: "CAKE Staked",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "Flexible APY",
        flexPerc: "2,79%",
        totalStaked: "Total staked",
        valueStaked: 244.762,
        cake: "CAKE",
        locked: "Locked APR",
        upto: "Up to 59.84%",
        nameBtn: "Auto",
        tLocked: "Total locked:",
    },
    {
        eventkey: "1",

        class: "btn-cake-2",
        id: 1,
        imgFarm: xIcon,
        title: "Earn XCAD",
        paraPool: "Stake CAKE",
        poolstaked: "XCAD Staked",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "5.84%",
        locked: "Total staked",
        upto: "5.727.974 CAKE",
        tLocked: "Total locked:",
        totalStaked: "End in",
        valueStaked: "1.927.256 Blocks",
        nameBtn: "Manuale"
    }, {
        eventkey: "2",
        id: 2,
        class: "btn-cake-2",
        imgFarm: iconpi,
        title: "Earn MGP",
        paraPool: "Stake CAKE",
        poolstaked: "MGP earned",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "5.91%",
        locked: "Total staked",
        upto: "5.969.484 CAKE",
        tLocked: "Total locked:",
        totalStaked: "End in",
        nameBtn: "Manuale",
        valueStaked: "2.447.529 Blocks",
    }, {
        eventkey: "3",
        id: 3,
        class: "btn-cake-2",
        imgFarm: iconLeon,
        title: "Earn WMX",
        paraPool: "Stake CAKE",
        poolstaked: "WMX earned",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "6.24%",
        locked: "Total staked",
        upto: "5.425.187 CAKE",
        tLocked: "Total locked:",
        totalStaked: "End in",
        valueStaked: "462.974 Blocks",
        nameBtn: "Manuale"
    },
    {
        eventkey: "4",
        id: 4,
        class: "btn-cake-2",
        imgFarm: iconsr,
        title: "Earn KRS",
        paraPool: "Stake CAKE",
        poolstaked: "KRS earned",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "6,09%",
        locked: "Total staked",
        upto: "3.462.215 CAKE",
        tLocked: "Total locked:",
        totalStaked: "End in",
        nameBtn: "Manuale",
        valueStaked: "328.741 Blocks",

    }
]