import iconFarm1 from "../../assets/images/iconFarm1.png";


import xIcon from "../../assets/images/xIcon.png";
import iconpi from "../../assets/images/iconpi.png"
import iconLeon from "../../assets/images/iconLeon.png"
import iconsr from "../../assets/images/iconsr.png"

export const poolsValue = [{
        eventkey: "0",
        id: 0,
        zero: 0,
        class: "btn-cake-acc",
        imgFarm: iconFarm1,
        title: "Stake-CAKE",
        paraPool: "Stake, Earn – And more!",
        poolstaked: "CAKE Staked",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "Flexible APY",
        flexPerc: "2,79%",
        totalStaked: "Total staked",
        valueStaked: "244.762.256 CAKE",
        cake: "RECENT CAKE PROFIT",
        lCake: "198.171.208 cake",
        locked: "Locked APR",
        upto: "Up to 59.84%",
        nameBtn: "Auto",
        tLocked: "Total locked:",
        week: "42 weeks",
        perfo: "Performance",
        fee: "fee 0~2%",
        start: "START STAKING",
        average: "Average lock duration:",
    },
    {
        eventkey: "1",
        zero: 0,
        cake: "CAKE",
        class: "btn-cake-2",
        id: 1,
        imgFarm: xIcon,
        title: "Earn XCAD",
        paraPool: "Stake CAKE",
        poolstaked: "XCAD Staked",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "5.84%",
        locked: "Total staked",
        average: "APR:",
        upto: "5.727.974 CAKE",
        week: "5.84%",
        totalStaked: "End in",
        valueStaked: "1.927.256 Blocks",
        nameBtn: "Manuale",
        perfo: "End in",
        fee: "1.927.256 Blocks",
        earned: "EARNED",
        start: "START STAKING",
    }, {
        eventkey: "2",
        zero: 0,
        cake: "CAKE",
        id: 2,
        earned: "EARNED",
        class: "btn-cake-2",
        imgFarm: iconpi,
        title: "Earn MGP",
        paraPool: "Stake CAKE",
        poolstaked: "MGP earned",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "5.91%",
        locked: "Total staked",
        upto: "5.969.484 CAKE",
        totalStaked: "End in",
        nameBtn: "Manuale",
        average: "APR:",
        week: "5.91%",
        valueStaked: "2.447.529 Blocks",
        perfo: "End in",
        fee: "2.447.529 Blocks",
        start: "START STAKING",
    }, {
        eventkey: "3",
        cake: "CAKE",
        zero: 0,
        earned: "EARNED",
        id: 3,
        class: "btn-cake-2",
        imgFarm: iconLeon,
        title: "Earn WMX",
        paraPool: "Stake CAKE",
        poolstaked: "WMX earned",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "6.24%",
        locked: "Total staked",
        upto: "5.425.187 CAKE",
        average: "APR:",
        totalStaked: "End in",
        valueStaked: "462.974 Blocks",
        nameBtn: "Manuale",
        week: "6.24%",
        perfo: "End in",
        fee: "462.974 Blocks",
        start: "START STAKING",
    },
    {
        eventkey: "4",
        id: 4,
        cake: "CAKE",
        zero: 0,
        class: "btn-cake-2",
        earned: "EARNED",
        imgFarm: iconsr,
        title: "Earn KRS",
        paraPool: "Stake CAKE",
        poolstaked: "KRS earned",
        poolN: 0.0,
        poolUsd: "0 USD",
        flexPool: "APR",
        flexPerc: "6,09%",
        locked: "Total staked",
        upto: "3.462.215 CAKE",
        week: "6.09%",

        average: "APR:",
        totalStaked: "End in",
        nameBtn: "Manuale",
        valueStaked: "328.741 Blocks",
        perfo: "End in",
        fee: "328.741  Blocks",
        start: "START STAKING",

    }
]